{"uuid": "78123ff5-f118-4170-a3a5-5e97bb15fa80", "children": ["74e68e1b-f869-4f82-9216-5db47b61b540"], "befores": [{"name": "_xunit_setup_method_fixture_TestUserAuth", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'logs/log_2023-04-23_11-01-53.log'\n", "trace": "  File \"/Users/akre-t/Library/Python/3.9/lib/python/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/akre-t/Library/Python/3.9/lib/python/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/akre-t/Library/Python/3.9/lib/python/site-packages/_pytest/fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/akre-t/Library/Python/3.9/lib/python/site-packages/_pytest/python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"/Users/akre-t/Library/Python/3.9/lib/python/site-packages/_pytest/python.py\", line 788, in _call_with_optional_argument\n    func()\n  File \"/Users/akre-t/Desktop/Ренат/Coding/testQa/testQA/tests/test_auth.py\", line 20, in setup\n    response1 = MyRequests.post(\n  File \"/Users/akre-t/Desktop/Ренат/Coding/testQa/testQA/lib/my_requests.py\", line 11, in post\n    return MyRequests._send(url,data,headers,cookies,'POST')\n  File \"/Users/akre-t/Desktop/Ренат/Coding/testQa/testQA/lib/my_requests.py\", line 34, in _send\n    Logger.add_request(url, data, headers, cookies, method)\n  File \"/Users/akre-t/Desktop/Ренат/Coding/testQa/testQA/lib/logger.py\", line 27, in add_request\n    cls._write_log_to_file(data_to_add)\n  File \"/Users/akre-t/Desktop/Ренат/Coding/testQa/testQA/lib/logger.py\", line 10, in _write_log_to_file\n    with open(cls.file_name, 'a', encoding='utf-8') as logger_file:\n"}, "steps": [{"name": "POST request to URL '/user/login'", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'logs/log_2023-04-23_11-01-53.log'\n", "trace": "  File \"/Users/akre-t/Desktop/Ренат/Coding/testQa/testQA/lib/my_requests.py\", line 11, in post\n    return MyRequests._send(url,data,headers,cookies,'POST')\n  File \"/Users/akre-t/Desktop/Ренат/Coding/testQa/testQA/lib/my_requests.py\", line 34, in _send\n    Logger.add_request(url, data, headers, cookies, method)\n  File \"/Users/akre-t/Desktop/Ренат/Coding/testQa/testQA/lib/logger.py\", line 27, in add_request\n    cls._write_log_to_file(data_to_add)\n  File \"/Users/akre-t/Desktop/Ренат/Coding/testQa/testQA/lib/logger.py\", line 10, in _write_log_to_file\n    with open(cls.file_name, 'a', encoding='utf-8') as logger_file:\n"}, "start": 1682236913692, "stop": 1682236913692}], "start": 1682236913692, "stop": 1682236913692}], "start": 1682236913692, "stop": 1682236913697}